### ISSUE TITLE
Return IconColorRGB in /api/v1/Trolleys/Running

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-api-dot-net#31]
It would simplify some of the front-end logic if we return the IconColorRGB in the 'Running' endpoint. That way I don't have to download the entire list of trolleys and loop through them to find the color of the running trolleys!

**Comment by bikeoid** [comment]
I've tried to minimize the size of communications with both the beacons and clients in the Running endpoint, including stripping off cookies.   There's a good chance that we'll have to move to Azure in the future, where bandwidth will be part of the direct cost.

Since there are only a few trolleys, can the trolley information be downloaded once and cached?

**Comment by ajhodges** [comment]
Ah, I see. If that's the case, then I certainly can cache trolley data! No problem.
