### ISSUE TITLE
Trolley color doesn't match any route

### ISSUE THREAD

**Issue by austin9350** [codeforgreenville/trolley-tracker-api-dot-net#36]
@bikeoid 

It looks like one of the Trolley colors doesn't match any Route color.

The Trolley in question shows as green on the map, and has ID 1, Number 6, IconColorRGB cfdf01.

It appears to be running the "Top of Main" route, RouteColorRGB acb71d (which is also green, but a different green).

I don't remember if I ever sent you the colors I was using in the app initially, but I think I had changed the green a bit (from the Greenlink color) to make it stand out more on the map. Possibly one of the colors is the official color, and one is the altered value I used?

**Comment by bikeoid** [comment]
I now have set the "Top of Main" trolley and route to the one in the IOS app (F7BD38), and it does stand out better in IOS, it's more of a harvest gold instead of light-green-yellow.   

I had originally set it on an uncalibrated monitor and contrasted against the leaflet Mapbox map but this color works better on a white map background, as well as leaflet.
