### ISSUE TITLE
Trolley not showing up on North Main loop sat 6/16 

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-api-dot-net#44]
I was downtown and saw one trolley running and show up, and the second which I also saw physically did not show up in app. We also got feedback that it wasn’t running.

Not sure if this was user error or system

**Comment by bikeoid** [comment]
The last option above is not an option for this year as the routes are fixed and will be studied for next year.

The first option above to poll other routes to find a missing trolley.   Display its color in Black since that is the most likely color to apply.   It still won't match the route colors to allow the user to highlight that route however.
