### ISSUE TITLE
Trolley not tracking 

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-api-dot-net#47]
I’ve got two user reports last night and tonight that the Trolleys aren’t tracking. They don’t se to be working for me either. New API issue? @bikeoid

**Comment by bikeoid** [comment]
Missed this earlier somehow, but this is still the Syncromatics server / tablet outage from https://github.com/codeforgreenville/trolley-tracker/issues/162 .   It's been working over the last 2 weekends but the arts Route wasn't showing last weekend.  I didn't track it down to see where the problem was, but the Greenlink app showed the same thing.

**Comment by ajhodges** [comment]
Trolley wasn't being tracked on lunch link today. FWIW
