### ISSUE TITLE
Route path travel time prediction

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-api-dot-net#7]
Design a system to collect the reported trolley location data in a way that it can be analyzed to predict travel times, and eventually arrival times at any particular user's stop.

**Comment by bikeoid** [comment]
Travel time history - flat text file with trolley location reports from 12/2015 through 5/22/2016.  https://www.dropbox.com/s/o623kliawf0dtzl/TrolleyLocationHistory.zip?dl=0

**Comment by dacohenii** [comment]
Plan of attack:

- API provides "most recently seen" data per stop per trolley
- clients handle calculation from there

**Comment by Linktheoriginal** [comment]
When the beacon pings the server, if the coordinates are within range of a stop (a range in the Lat/Long coordinates from the stop's Lat/Long), we update the stop with the last visit time.  We maintain the last visit time on each stop per Trolley ID.

This information will be sent along with the stop data, and the client should do some sanity checking before displaying the data (don't show anything too large, for instance if a trolley detours around a stop).  The UI will be to show the estimated arrival time on each stop when stop information is shown (when the user clicks on a stop, we show the estimated time along with the name, etc.)  It's optional to show the estimated time for each trolley or just the closest.

If there are two routes being run, the most recent visited data by trolley should be able to inform the client that the trolley hasn't been running a given route.

We discussed averaging historical time per stop, but agreed that the more recent data was the most useful (if there's an accident, the historical data would be a much lower number than the current time).

Typically the Trolleys take 25-30 minutes to complete the main loop, and when two are running, it's about 15 minutes per each stop.  If the data is wrong, default to showing nothing.  Make sure that we show in the UI that this is just an estimation based on the last time the trolley went.  The estimated times provided should err towards showing too short of a time instead of too long of a time.

For POIs, I'm adding a MapBox provided layer to the webapp, and the iOS app already had a number of POIs I believe.

**Comment by bikeoid** [comment]
Still itching to implement this, but client keeps adding emergency needs; hope to get to this soon.

**Comment by bikeoid** [comment]
This is running on the dev server at http://yeahthattrolley.azurewebsites.net/ , but has not yet been published to the production server.   There is a new element added to the stop JSON, consisting of each trolley (by trolley number, not ID), paired with the last time seen at that stop.   Here are some sample formats depending of 2, 1, or 0 trolleys have passed:  
```
LastTrolleyArrivalTime":{"999":"2016-08-28T20:42:19.1737862","5":"2016-08-28T21:14:01.5996718"}

LastTrolleyArrivalTime":{"999":"2016-08-28T20:55:08.5781036"}

LastTrolleyArrivalTime":{}

```

**Comment by dacohenii** [comment]
Could we get the API to populate the `LastTrolleyArrivalTime` for the stops listed on the `Routes` endpoints (for each individual route)? 

Currently, both `http://yeahthattrolley.azurewebsites.net/api/v1/Stops` and `http://yeahthattrolley.azurewebsites.net/api/v1/Routes/1` include this, but it's only populated for `/Stops`.

**Comment by bikeoid** [comment]
Version 1.2.5 is now on the server, which implements LastTrolleyArrivalTime for routes

**Comment by jeremywight** [comment]
🙌👊👏

**Comment by bikeoid** [comment]
I have an implementation of this on the dev system at http://yeahthattrolley.azurewebsites.net/ / the DB Visualizer.   Decoding from arrival time to travel prediction turns out to be extremely hairy - look at the Javascript (or better yet, don't look!).   Click on the stop to view the arrival time information., if available   

There are dozens of ways to fake out the calculations as I have implemented, so they are often wrong here, partly because of the simulated data.   I expect more consistent behavior on the real trolleys after the first round.   This has not yet been published on the real server - I hope it is published before the next weekend's trolley runs.

**Comment by jeremywight** [comment]
Note: You can only see the arrival information if the trolley is running.

@bikeoid will you be able to join us next week? Would love to discuss!

**Comment by bikeoid** [comment]
Yes I'll be there.   I've got the simulation running with the classic route.    In the simulation, many stops aren't seeing arrival times.   I think this is because the app goes to sleep on the server and I don't store the info to the database.

**Comment by jeremywight** [comment]
How is the data being stored, in mem-cache?

**Comment by bikeoid** [comment]
The times are currently stored in mem cache, which seems to work while the trolleys run in the real app.  At the moment, most stops have travel times in the Dev instance when clicking on the stop.

**Comment by jeremywight** [comment]
Thanks for the clarification @bikeoid!

**Comment by bikeoid** [comment]
I got a chance to check tonight's run (Thursday).   It has already been fooled by the 'downtown live' detour, in which it goes near the Richardson St garage on the way back.  That causes my "trolley position detection " to fail because I see the time blip there.    At times it cannot even calculate because of that problem (I don't display times if they are negative).

Also found that there is a bug in Leaflet / Chrome, in which the stop popup won't change, ever.   I do see times coming up in Edge and Firefox after 1 minute.     I noticed that the trolley won't follow the detour next time so it might work.

**Comment by bikeoid** [comment]
It works somewhat on the regular route!    It also gets temporarily confused when it passes the stops northbound on N Main near Stone Ave, but straightens out when it passes those stops southbound.

**Comment by bikeoid** [comment]
There are a number of problems in trying to use the arrival times as implemented today - much of the logic would need to exist in the clients, and implemented 3 times among the 3 clients.

We discussed an alternative to simplify the client side implementation, and have this alternative:

Server would predict the arrival time for each stop, and what is passed today as most recent arrival time for each trolley would instead become the predicted arrival time.

The server also needs to add a further check when passing a stop so that only stops on the right side of the travel path are considered.

**Comment by bikeoid** [comment]
Food for thought https://youtu.be/0KZvJ4HbmH4 , watch it full screen to read the text - I still find too many cases where it's way off, but it works better on these circular routes than the previous routes.

**Comment by bikeoid** [comment]
This is running on the Dev server now - click on a stop in the DB Visualizer after it's been displayed for a minute to view stop times.   Arrival time is sent to the client in a new field: NextTrolleyArrivalTime, as in:

ID:	52
Name:	"Falls Park Drive"
Description:	"Falls Park Drive"
Lat:	34.8457675640172
Lon:	-82.40255981683733
ShapeSegmentIndex:	null
StopImageURL:	null
NextTrolleyArrivalTime:	
5	"2018-01-20T08:13:32.4573159"
6	"2018-01-20T08:29:50.5090777"
1701	"2018-01-20T08:30:24.6702572"
1702	"2018-01-20T08:26:59.5628604"

It hasn't been published to production yet, but will be next week where we can see if there are any issues when the drivers go on break, etc.    I tested it on Lunch Link on Friday and it worked OK - a bit confusing because there are no "official stops" northbound on Main Street, so the stop time is shown when the trolley is southbound, even though the drivers will unofficially treat the space across the street as a northbound stop.
